import Head from 'next/head'
import { FC } from 'react'
import styles from './MainLayout.module.css'
import MainLayoutProps from './MainLayout.types'
import Nabvar from 'components/Nabvar'

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gio Sosa - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nabvar />

      <main className={styles.main}>{children}</main>
    </div>
  )
}

export default MainLayout
