name: Build
on: 
  pull_request:
    types: 
      - opened
    branches:
      - master
  workflow_dispatch: 
    inputs:
      env-select:
        required: true
        default: 'all'
        description: Select environment (Default all)
        type: choice
        options:
          - all
          - staging
          - qa
          - dev



jobs:
  build:
    if: ${{(inputs.env-select == 'all') || (inputs.env-select == 'staging') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Conditional ${{(inputs.env-select == 'all') || (inputs.env-select == 'staging') }}"
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
 
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build

  build-2:
    if: ${{(inputs.env-select == 'all') || (inputs.env-select == 'qa') || (github.event == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Conditional ${{(inputs.env-select == 'all') || (inputs.env-select == 'qa') || (github.event == 'pull_request') }}"
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
 
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build

  build-dev:
    if: ${{(inputs.env-select == 'all') || (inputs.env-select == 'dev') || (github.event == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Conditional ${{(inputs.env-select == 'all') || (inputs.env-select == 'dev') || (github.event == 'pull_request') }}"
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
 
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build